import { Game } from '../models/game'
import { Results } from '../models/results'
import { Submission } from '../models/submission'

export const mockGamesSearchResult: Game[] = [
  { id: '1', title: 'Sierra' },
  { id: '2', title: 'Eric' },
  { id: '3', title: 'Kristina' },
  { id: '4', title: 'Andrew' },
  { id: '5', title: 'Patrick' },
  { id: '6', title: 'Ashleigh' },
  { id: '7', title: 'Bryce' },
  { id: '8', title: 'Emmett' },
  { id: '9', title: 'Prairie' },
  { id: '10', title: 'Alex' },
  { id: '11', title: 'Cody' },
  { id: '12', title: 'Aric' },
]

export const theSubmission: Submission = {
  submissionUUID: '253956d5-9768-4056-b946-9d27e4e04d78',
  name: 'Kherven',
  gamesOfTheYear: [
    { id: '8', title: 'Emmett' },
    { id: '9', title: 'Prairie' },
    { id: '10', title: 'Alex' },
    { id: '11', title: 'Cody' },
    { id: '12', title: 'Aric' },
  ],
  bestOldGame: { id: '447', title: 'SMITE' },
  mostAnticipated: { id: '225', title: 'Battlefield 2048' },
  enteredGiveaway: true,
}

export const allSubmissions: Submission[] = [
  {
    submissionUUID: '253956d5-9768-4056-b946-9d27e4e04d78',
    name: 'Kherven',
    gamesOfTheYear: [
      { id: '4', title: 'Andrew' },
      { id: '5', title: 'Patrick' },
      { id: '6', title: 'Ashleigh' },
    ],
    bestOldGame: { id: '447', title: 'SMITE' },
    mostAnticipated: { id: '225', title: 'Battlefield 2048' },
    enteredGiveaway: true,
  },
  {
    submissionUUID: 'de7a00a4-1f3b-11ec-9621-0242ac130002',
    name: 'Sierra',
    gamesOfTheYear: [
      { id: '8', title: 'Emmett' },
      { id: '9', title: 'Prairie' },
      { id: '10', title: 'Alex' },
      { id: '11', title: 'Cody' },
      { id: '12', title: 'Aric' },
    ],
    bestOldGame: { id: '221', title: 'Animal Crossing' },
    mostAnticipated: { id: '777', title: 'Java' },
    enteredGiveaway: false,
  },
  {
    submissionUUID: 'da94c4ba-1f3b-11ec-9621-0242ac130002',
    name: 'Eric',
    gamesOfTheYear: [
      { id: '1', title: 'Sierra' },
      { id: '2', title: 'Eric' },
      { id: '3', title: 'Kristina' },
      { id: '4', title: 'Andrew' },
      { id: '5', title: 'Patrick' },
      { id: '6', title: 'Ashleigh' },
      { id: '7', title: 'Bryce' },
      { id: '8', title: 'Emmett' },
      { id: '9', title: 'Prairie' },
    ],
    bestOldGame: { id: '876', title: 'KOTOR' },
    mostAnticipated: { id: '176`', title: 'Veracode' },
    enteredGiveaway: true,
  },
]

export const theResults: Results = {
  participants: [
    'Twister',
    'BoomBot',
    'Mr X',
    'Andrew E. Savadge',
    'Warpath',
    'uni',
    'Magnus',
    'Rurin',
    'Rake',
    'Belmon',
    'Kherven',
  ],
  bestOldGames: [
    {
      id: '0',
      rank: 0,
      title: 'Minecraft',
      votes: 3,
    },
    {
      id: '1',
      rank: 1,
      title: 'SMITE',
      votes: 2,
    },
    {
      id: '2',
      rank: 2,
      title: 'Breath of the Wild',
      votes: 1,
    },
    {
      id: '3',
      rank: 2,
      title: 'Total War: Warhammer II',
      votes: 1,
    },
    {
      id: '4',
      rank: 2,
      title: 'overwatch',
      votes: 1,
    },
    {
      id: '5',
      rank: 2,
      title: 'Sea of Thieves',
      votes: 1,
    },
    {
      id: '6',
      rank: 2,
      title: 'Pillars of Eternity 2',
      votes: 1,
    },
    {
      id: '7',
      rank: 2,
      title: 'Stellaris',
      votes: 1,
    },
  ],
  mostAnticipated: [
    {
      id: '0',
      rank: 0,
      title: 'Cyberpunk 2077',
      votes: 3,
    },
    {
      id: '1',
      rank: 1,
      title: 'SMITE',
      votes: 1,
    },
    {
      id: '2',
      rank: 1,
      title: 'Breath of the Wild',
      votes: 1,
    },
    {
      id: '3',
      rank: 1,
      title: 'Total War: Warhammer II',
      votes: 1,
    },
    {
      id: '4',
      rank: 1,
      title: 'overwatch',
      votes: 1,
    },
    {
      id: '5',
      rank: 1,
      title: 'Sea of Thieves',
      votes: 1,
    },
    {
      id: '6',
      rank: 1,
      title: 'Pillars of Eternity 2',
      votes: 1,
    },
    {
      id: '7',
      rank: 1,
      title: 'Stellaris',
      votes: 1,
    },
  ],
  gamesOfTheYear: [
    {
      id: '0',
      rank: 0,
      title: 'Apex Legends',
      votes: 8,
      points: 108,
    },
    {
      id: '0',
      rank: 1,
      title: 'Outward',
      votes: 3,
      points: 31,
    },
    {
      id: '0',
      rank: 2,
      title: 'Mordhau',
      votes: 3,
      points: 25,
    },
    {
      id: '0',
      rank: 3,
      title: 'Risk of Rain 2',
      votes: 2,
      points: 28,
    },
    {
      id: '0',
      rank: 4,
      title: 'Sekiro: Shadows Die Twice',
      votes: 2,
      points: 20,
    },
    {
      id: '0',
      rank: 5,
      title: 'The Outer Worlds',
      votes: 2,
      points: 19,
    },
    {
      id: '0',
      rank: 6,
      title: 'World of Warcraft: Classic',
      votes: 2,
      points: 18,
    },
    {
      id: '0',
      rank: 7,
      title: 'Kingdom Hearts 3',
      votes: 2,
      points: 16,
    },
    {
      id: '0',
      rank: 8,
      title: 'Pokemon Sword and Shield',
      votes: 2,
      points: 14,
    },
    {
      id: '0',
      rank: 9,
      title: 'Crash Team Racing',
      votes: 2,
      points: 15,
    },
    {
      id: '0',
      rank: 10,
      title: 'Death Stranding',
      votes: 1,
      points: 15,
    },
    {
      id: '0',
      rank: 11,
      title: 'GreedFall',
      votes: 1,
      points: 15,
    },
    {
      id: '0',
      rank: 12,
      title: 'ACE COMBAT™ 7: SKIES UNKNOWN',
      votes: 1,
      points: 15,
    },
    {
      id: '0',
      rank: 13,
      title: 'Borderlands 3',
      votes: 1,
      points: 13,
    },
  ],
  giveawayEntries: [
    'BoomBot',
    'Mr X',
    'Andrew E. Savadge',
    'uni',
    'Magnus',
    'Rurin',
    'Belmon',
  ],
}

export const searchResults: Game[] = [
  { id: '1', title: 'Sierra' },
  { id: '2', title: 'Eric' },
  { id: '3', title: 'Kristina' },
  { id: '4', title: 'Andrew' },
  { id: '5', title: 'Patrick' },
  { id: '6', title: 'Ashleigh' },
  { id: '7', title: 'Bryce' },
  { id: '8', title: 'Emmett' },
  { id: '9', title: 'Prairie' },
  { id: '10', title: 'Alex' },
  { id: '11', title: 'Cody' },
  { id: '12', title: 'Aric' },
]
