### Update properties
PUT http://localhost:8080/properties
Content-Type: application/json

{
  "tiePoints": [15, 13, 11],
  "deadline": "2022-11-06T13:01:44-06:00",
  "hasGiveaway": false,
  "giveawayAmountUSD": 15
}
